# Generated by Django 5.2 on 2025-06-08 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cliente_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='lido',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='icone',
            field=models.CharField(default='🔔', max_length=10),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
