# Generated by Django 5.2 on 2025-06-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_exercicio_registrocarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocarga',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='repeticoes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='series',
            field=models.IntegerField(),
        ),
    ]
