# Generated by Django 5.2.2 on 2025-06-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_registrocarga_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='carga',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='repeticoes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
