# Generated by Django 5.2.2 on 2025-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_medicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='parte_corpo',
            field=models.CharField(choices=[('braco_direito', 'Braço Direito'), ('braco_esquerdo', 'Braço Esquerdo'), ('peito', 'Peitoral'), ('cintura', 'Cintura'), ('quadril', 'Quadril'), ('coxa_direita', 'Coxa Direita'), ('coxa_esquerda', 'Coxa Esquerda'), ('panturrilha_direita', 'Panturrilha Direita'), ('panturrilha_esquerda', 'Panturrilha Esquerda'), ('peso', 'Peso')], max_length=30),
        ),
    ]
