# Generated by Django 5.2.2 on 2025-06-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_medicao_parte_corpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(choices=[('Hipertrofia', 'Hipertrofia'), ('Emagrecimento', 'Emagrecimento'), ('Condicionamento', 'Condicionamento')], max_length=50)),
                ('nome', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='main.treinopadrao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
