# Generated by Django 5.2.2 on 2025-06-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_treinopadrao_exerciciopadrao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExercicioPadrao',
        ),
        migrations.DeleteModel(
            name='TreinoPadrao',
        ),
    ]
