# Generated by Django 5.2.2 on 2025-06-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_treinopersonalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinopersonalizado',
            name='repeticoes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treinopersonalizado',
            name='series',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
