# Generated by Django 5.2.2 on 2025-06-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_planonutricional'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente'),
        ),
    ]
