# Generated by Django 5.2.2 on 2025-06-19 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notificacao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='planonutricional',
            name='refeicao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planonutricional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
    ]
