# Generated by Django 5.2.2 on 2025-06-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_planonutricional_refeicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planonutricional',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
