# Generated by Django 5.2.2 on 2025-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_planonutricional_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
