# Generated by Django 5.2.2 on 2025-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_nutricionista_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restricoes_alimentares',
            field=models.TextField(blank=True, null=True),
        ),
    ]
