# Generated by Django 5.2.2 on 2025-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_restricoes_alimentares'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='nutricionistas/fotos/'),
        ),
    ]
